name: RevBayes
author: RevBayes
markdown: redcarpet
pygments: true
baseurl: http://revbayes.github.io
description: Bayesian graphical models
github: http://www.github.com/revbayes
twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: revbayes[at]github.com
#location: 42°2'16"N   70°12'47"W
#disqus: diqus-username
##Make sure to edit the above fields, especially for disqus.

